apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wisecow-tls
  namespace: default
spec:
  secretName: wisecow-tls
  dnsNames:
  - wisecow.yourdomain.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
